name: flutter_app
description: This is a flutter starter app for quick format builder.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.4.1
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Lora
      fonts:
        - asset: fonts/lora/bold.ttf
          weight: 700
        - asset: fonts/lora/bold_italic.ttf
          weight: 700
          style: italic
        - asset: fonts/lora/italic.ttf
          style: italic
        - asset: fonts/lora/medium.ttf
        - asset: fonts/lora/medium_italic.ttf
        - asset: fonts/lora/regular.ttf
        - asset: fonts/lora/semi_bold.ttf
        - asset: fonts/lora/semi_bold_italic.ttf
          style: italic
        - asset: fonts/lora/variable.ttf
        - asset: fonts/lora/variable_italic.ttf
          style: italic

    - family: Arial
      fonts:
        - asset: fonts/arial/bold.ttf